### 元素计算函数

#### 1. ceil(): 向上最接近的整数，参数是number或array

In [1]:
import numpy as np

In [3]:
arr = np.random.randn(2, 3)
print(arr)

[[ 1.10290275 -0.00894136  0.16760675]
 [ 0.86214914 -1.72315963 -0.02785111]]


In [4]:
print(np.ceil(arr))

[[ 2. -0.  1.]
 [ 1. -1. -0.]]


#### 2. floor():向下最接近的整数，参数是number或array

In [5]:
print(np.floor(arr))

[[ 1. -1.  0.]
 [ 0. -2. -1.]]


#### 3. rint(): 四舍五入, 参数是number或array

In [6]:
print(np.rint(arr))

[[ 1. -0.  0.]
 [ 1. -2. -0.]]


#### 4. isnan(): 判断元素是否为NaN(Not a Number), 参数是number或array

In [7]:
print(np.isnan(arr))

[[False False False]
 [False False False]]


#### 5. multiply(): 元素相乘，参数为number或array

In [8]:
print(np.multiply(arr, arr))

[[1.21639448e+00 7.99479270e-05 2.80920215e-02]
 [7.43301132e-01 2.96927910e+00 7.75684566e-04]]


#### 6. divide(): 元素相除，参数是number或array

In [9]:
print(np.divide(arr, arr))

[[1. 1. 1.]
 [1. 1. 1.]]


#### 7. abs(): 元素的绝对值，参数是number或array

In [10]:
print(np.abs(arr))

[[1.10290275 0.00894136 0.16760675]
 [0.86214914 1.72315963 0.02785111]]


#### 8. where(condition, x, y): 三元运算，x if condition else y

In [11]:
print(np.where(arr >0, 1, -1))

[[ 1 -1  1]
 [ 1 -1 -1]]


### 元素统计函数

#### 1. np.mean(), np.sum(): 所有元素的平均值，所有元素的和。参数number或array

In [29]:
arr = np.arange(12).reshape(3, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
print(np.mean(arr, axis=1), np.sum(arr, axis=1))

[1.5 5.5 9.5] [ 6 22 38]


#### 2. np.max(), np.min(): 所有元素的最大值，所有元素的最小值，参数是number或array

In [19]:
print(np.max(arr, axis=1), np.min(arr, axis=1))

[ 3  7 11] [0 4 8]


#### 3. np.std, np.var(): 所有元素的标准差，所有元素的方差，参数是number或array

In [21]:
print(np.std(arr, axis=1), np.var(arr, axis=1))

[1.11803399 1.11803399 1.11803399] [1.25 1.25 1.25]


#### 4. np.argmax(), np.argmin(): 最大值的下标索引值，最小值的小标索引值，参数。。。

In [27]:
print(np.argmax(arr, axis=1), np.argmin(arr, axis=1))

[3 3 3] [0 0 0]


#### 5. np.cumsum(), np.cumprod(): 返回一个数组，每个元素都是之前元素的累加，乘积。

In [34]:
print(np.cumsum(arr), np.cumprod(arr))

[ 0  1  3  6 10 15 21 28 36 45 55 66] [0 0 0 0 0 0 0 0 0 0 0 0]


#### 6. 多维数组默认统计全部维度，axis参数可以按指定轴心统计，0按照列统计，1按照行统计

### 元素判断函数

#### 1. np.any(): 至少有一个元素满足指定条件，返回True

#### 2. np.all(): 所有的元素满足指定条件，返回True

In [35]:
arr = np.random.randn(2,3)
print(arr)

[[-1.06708246  1.18382882 -1.06901106]
 [ 1.384129   -1.06874513  1.28499303]]


In [36]:
print(np.any(arr > 0))
print(np.all(arr > 0))

True
False


### 元素去重排序函数

#### np.unique():找到唯一值并返回排序结果，类似于Python的set集合

In [37]:
arr = np.array([[1, 2, 1], [2, 3, 4]])
print(arr)

print(np.unique(arr))

[[1 2 1]
 [2 3 4]]
[1 2 3 4]
