### ndarray的矩阵运算

#### 数组是编程的概念，矩阵、矢量是数学概念

In [1]:
# 在计算机编程中，矩阵可以用数组形式定义，矢量可以用结构定义

#### 1. 矢量运算：相同大小的数组间运算应用在元素上

In [1]:
import numpy as np

In [2]:
# 矢量与矢量运算
arr = np.array([[1, 2, 3], 
                        [4, 5, 6]])

print("元素相乘：\n", arr * arr)      # 对应元素相乘

元素相乘：
 [[ 1  4  9]
 [16 25 36]]


In [3]:
print("矩阵相加：\n", arr + arr)      # 对应元素相加

矩阵相加：
 [[ 2  4  6]
 [ 8 10 12]]


#### 2. 矢量和标量运算:“广播”-将标量“广播”到各个元素

In [4]:
print(1. / arr)
print('--------------------------')
print(2 * arr)
print('-----------')
print(1 + arr)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
--------------------------
[[ 2  4  6]
 [ 8 10 12]]
-----------
[[2 3 4]
 [5 6 7]]


### ndarray 的索引与切片

#### 1. 一维数组的索引与切片

In [5]:
# 一维数组
arr1 = np.arange(10)
print(arr1)
print(arr1[2: 5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [6]:
# 多维数组
arr2 = np.arange(12).reshape(3, 4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
print(arr2[1])
print('---------------------')
print(arr2[:2, 2:])
print('---------------------')
print(arr2[:, 1:3])

[4 5 6 7]
---------------------
[[2 3]
 [6 7]]
---------------------
[[ 1  2]
 [ 5  6]
 [ 9 10]]


#### 3. 条件索引

In [8]:
# 找出data_arr 中2005年后的数据
data_arr = np.random.rand(3, 3)
print(data_arr)

[[0.86040983 0.44288625 0.04603144]
 [0.28423628 0.8522316  0.96169743]
 [0.09042964 0.56111426 0.04439945]]


In [9]:
year_arr = np.array([[2000, 2001, 2000], 
                                 [2005, 2002, 2009], 
                                 [2001, 2003, 2010]])
is_year_after_2005 = year_arr >= 2005
print(is_year_after_2005, type(is_year_after_2005))

[[False False False]
 [ True False  True]
 [False False  True]] <class 'numpy.ndarray'>


In [10]:
filtered_arr = data_arr[is_year_after_2005]
print(filtered_arr)

[0.28423628 0.96169743 0.04439945]


In [11]:
# filtered_arr = data_arr[year_arr >= 2005]
# print(filtered_arr)

In [12]:
# 多个条件
filtered_arr = data_arr[(year_arr <= 2005) | (year_arr % 2 == 0)]
print(filtered_arr)

[0.86040983 0.44288625 0.04603144 0.28423628 0.8522316  0.09042964
 0.56111426 0.04439945]


#### ndarray的为数转换

In [13]:
# 二维数组直接使用转换函数：transpose()
# 高维数组转换要指定维度编号(索引)参数 (0, 1, 2, …)，注意参数是元组

In [21]:
arr = np.random.rand(2, 3)      # 2x3 的数组
print(arr)
print('-' * 40)
print(arr.transpose())                # 转换成3x2 的数组

[[0.63781886 0.13057821 0.27157378]
 [0.32633258 0.37797754 0.23570454]]
----------------------------------------
[[0.63781886 0.32633258]
 [0.13057821 0.37797754]
 [0.27157378 0.23570454]]


In [19]:
arr3d = np.random.rand(2, 3, 4)      # 2x3x4 数组，2对应0，3对应1，4对应3
print(arr3d)
print('-' * 59)
print(arr3d.transpose(1, 0, 2))           # 根据维度编号，转为为 3x2x4 数组

[[[0.0697927  0.33672676 0.91155314 0.19607717]
  [0.59057105 0.58386236 0.32783447 0.06159591]
  [0.65199752 0.4770871  0.71692946 0.98575889]]

 [[0.43270253 0.02888324 0.58066607 0.52176731]
  [0.86128975 0.68478374 0.90302592 0.08555191]
  [0.46778206 0.83382165 0.65792146 0.97548202]]]
-----------------------------------------------------------
[[[0.0697927  0.33672676 0.91155314 0.19607717]
  [0.43270253 0.02888324 0.58066607 0.52176731]]

 [[0.59057105 0.58386236 0.32783447 0.06159591]
  [0.86128975 0.68478374 0.90302592 0.08555191]]

 [[0.65199752 0.4770871  0.71692946 0.98575889]
  [0.46778206 0.83382165 0.65792146 0.97548202]]]
