#### N Dimension Array 多维数组

In [1]:
# 导入Numpy
import numpy as np

In [77]:
# 生成指定维度大小（3x4）的随机浮点型数据（二维），rand固定区间（0.0，1.0）
arr_rand = np.random.rand(3, 4)
print(arr_rand, type(arr_rand))

[[0.08923921 0.18521729 0.78283158 0.53777477]
 [0.86864044 0.67196051 0.09701109 0.77009173]
 [0.54557921 0.3668708  0.8729727  0.35316623]] <class 'numpy.ndarray'>


In [41]:
# 生成指定维度大小（3x4）的随机多维整型数据（二维），randint可以指定区间（-1，5）
arr_randint = np.random.randint(-1, 5, size=(3, 4))
print(arr_randint, type(arr_randint))

[[-1  4 -1  4]
 [ 2 -1 -1  0]
 [ 1 -1 -1 -1]] <class 'numpy.ndarray'>


In [39]:
# 生成指定维数大小（3x4）的随机多维浮点数数据（二维），uniform可以指定区间（-1，5）
arr_uniform = np.random.uniform(-1, 5, size=(3, 4))
print(arr_uniform, type(arr_uniform))

[[-0.22502354  2.63916325  3.3540959   0.92181071]
 [ 2.8315129   1.82710568 -0.11167255  1.06732451]
 [ 0.21337963  3.46503092  1.35692312  1.59073243]] <class 'numpy.ndarray'>


In [42]:
print('维度个数', arr_randint.ndim)
print('维度大小', arr_randint.shape)
print('数据类型', arr_randint.dtype)

维度个数 2
维度大小 (3, 4)
数据类型 int32


#### ndarray 的序列创建

#### 1. np.array(collection)

In [72]:
# collection 为 序列型对象(list)、嵌套序列对象(list of list)。

In [11]:
# list序列转换为ndarray
lis = range(10)
arr = np.array(lis)

print(arr)              # ndarray数据
print(arr.ndim)     # 维度个数
print(arr.shape)    # 维度大小

[0 1 2 3 4 5 6 7 8 9]
1
(10,)


In [45]:
# list to list 嵌套序列转换为ndarray
lis_lis = [range(10), range(10)]
arr = np.array(lis_lis)

print(arr)              # ndarray数据
print(arr.ndim)     # 维度个数
print(arr.shape)    # 维度大小

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
2
(2, 10)


#### 2. np.zeros()

In [50]:
arr_zeros = np.zeros((3,4))
print(arr_zeros)
print(arr_zeros.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


#### 3. np.zeros()

In [53]:
arr_ones = np.ones((3,4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 4. empty()

In [55]:
arr_empty = np.empty((3, 4), int)
print(arr_empty)

[[ 1  2  2  1]
 [-1  2  0  1]
 [ 0  3  0 -1]]


#### 5. np.arange() 和 reshape()

In [57]:
# np.arange()
arr = np.arange(15)     # 15个元素的一维数组

print(arr, type(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] <class 'numpy.ndarray'>


In [58]:
print(arr.reshape(3, 5))    # 3x5个元素的二维数组

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [61]:
print(arr.reshape(1, 3, 5))    # 1x3x5个元素的三维数组

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]


   #### 6. np.arrange() 和 random.shuffle()

In [62]:
# randdom.shuffle() 将打乱数组序列（类似于洗牌）

In [64]:
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [65]:
np.random.shuffle(arr)

In [67]:
print(arr.reshape(3,5))

[[10  3  1  9  7]
 [ 8 13  2  4 11]
 [ 0  6  5 12 14]]


### ndarray的数据类型

In [68]:
# 1. dtype参数：指定数据组类型，类型名+位数，如float64，int32

In [69]:
# 2. astype方法：转换数据类型

In [70]:
# 初始化3行4列数组，数据类型为float64
zeros_float_arr = np.zeros((3, 4), dtype=np.float64)
print(zeros_float_arr)
print(zeros_float_arr.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [71]:
# astype转换数据类型，将已有的数组的数据类型转换为int32
zeros_int_arr = zeros_float_arr.astype(np.int32)
print(zeros_int_arr)
print(zeros_int_arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32
